"""
IP FORGE: Orchestrator State Models
Strictly typed data schemas representing agent execution state, planning DAGs, and task progression.
"""

from typing import List, Dict, Optional, Literal, Any
from pydantic import BaseModel, Field
from datetime import datetime, timezone


class PlanStep(BaseModel):
    """Discrete, actionable engineering step in an execution plan."""
    step_number: int
    action: Literal["read_file", "modify_file", "create_file", "run_test"] = Field(
        description="Type of operation to perform on the codebase"
    )
    target_file: str = Field(description="Relative path of file being inspected, edited, or tested")
    description: str = Field(description="Clear explanation of the change or verification required")
    symbols_involved: List[str] = Field(
        default_factory=list,
        description="Specific AST classes, functions, or methods touched by this step"
    )
    status: Literal["pending", "in_progress", "completed", "failed"] = "pending"
    execution_notes: Optional[str] = None


class EngineeringPlan(BaseModel):
    """Complete structured engineering plan generated by the Planner Agent."""
    task: str
    architectural_summary: str = Field(description="High-level understanding of existing systems and required changes")
    files_to_modify: List[str] = Field(description="Unique list of files that will be touched")
    steps: List[PlanStep] = Field(description="Ordered sequence of execution steps")
    verification_strategy: str = Field(description="How changes will be tested and verified")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AgentState(BaseModel):
    """Global multi-agent execution state passed through the state machine."""
    session_id: str
    task: str
    plan: Optional[EngineeringPlan] = None
    current_step_index: int = 0
    file_context: Dict[str, str] = Field(default_factory=dict, description="Cached file contents keyed by path")
    test_stdout: Optional[str] = None
    test_stderr: Optional[str] = None
    tests_passed: bool = False
    retry_count: int = 0
    max_retries: int = 3
    git_branch: Optional[str] = None
    git_diff: Optional[str] = None
    audit_trail: List[str] = Field(default_factory=list)
    status: Literal["planning", "coding", "testing", "debugging", "reviewing", "completed", "failed", "escalate_to_human"] = "planning"

    def record_event(self, event: str):
        """Appends timestamped log entry to the agent audit trail."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
        self.audit_trail.append(f"[{timestamp}] {event}")

